name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: make check
      working-directory: .  # Set the working directory to the root directory

    - name: Format
      run: make format
      working-directory: .  # Set the working directory to the root directory

    - name: Test
      run: make test
      working-directory: .  # Set the working directory to the root directory

    - name: Release
      run: make release
      working-directory: .  # Set the working directory to the root directory

    # Upload the binary file as an artifact
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binary
        path: ./sqlite/target/release/sqlite  # Assuming the binary is built in sqlite/target/release
